name: "Custom Build"
description: "Builds The Project"
inputs:
  languages:
    description: "Language"
    required: true
runs:
  using: "composite"
  steps:
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
