name: "CodeQL Reusable Workflow"

# this workflow can be stored in a centralized repo and called externally
# jobs:
#  code_analysis:
#    uses: [REPO]/.github/workflows/code_analysis.yml@main

on:
  workflow_call:     #for composition

jobs:
  # separate into an action
  detect-lang:
    runs-on: ubuntu-latest
    outputs:
      codeql_languages:   ${{ steps.codeql_languages.outputs.languages }}
    steps:
    - id: codeql_languages
      # builds the list of languages which are both present in the repo and supported by CodeQL
      # remove from the dictionary the languages that should not be considered (e.g .-[null, "go"])
      run: |
        echo "::set-output name=languages::$(gh api repos/{owner}/{repo}/languages -q '[
        {"C":"cpp", "C++":"cpp", "C#":"csharp", "Go":"go", "Java":"java", "JavaScript":"javascript", 
        "TypeScript":"javascript", "Python":"python", "Ruby":"ruby"}[keys[]]] | unique -[null]')"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  codeql-analysis:
    needs: [detect-lang]
    # skip the analysis when the list of languages is empty
    if: needs.detect-lang.outputs.codeql_languages != '[]'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(needs.detect-lang.outputs.codeql_languages) }}
        # exclude:
        #  - language: ruby
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Check CodeQL config existence
      id: custom_codeql_config
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/codeql/codeql-config.yml"
        
    - name: Initialize CodeQL default
      if: steps.custom_codeql_config.outputs.files_exists == 'false'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: mbaluda-org/security_team/codeql-config.yml@main
        debug: true
        
    - name: Initialize CodeQL custom
      if: steps.custom_codeql_config.outputs.files_exists == 'true'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql/codeql-config.yml
        debug: true    

    - name: Check local build action existence
      id: custom_build_action
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/actions/custom_build/action.yml"

    - name: Build default
      if: steps.custom_build_action.outputs.files_exists == 'false'
      uses: github/codeql-action/autobuild@v2

    - name: Build custom
      if: steps.custom_build_action.outputs.files_exists == 'true'
      uses: ./.github/actions/custom_build
      with:
        languages: ${{ matrix.language }}

    # perform the analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
