name: "CodeQL Reusable Workflow"

# this workflow can be stored in a centralized repo and called externally
# jobs:
#  code_analysis:
#    uses: [REPO]/.github/workflows/code_analysis.yml@main

on:
  workflow_call:
    inputs:
      exclude_codeql_languages:
        description: 'Languages that should not be analyzed'
        default: '[]'
        required: false
        type: string  

jobs:
  detect-lang:
    runs-on: ubuntu-latest
    outputs:
      codeql_languages: ${{ steps.codeql_languages.outputs.languages }}
    steps:
    - id: codeql_languages
      uses: mbaluda/codeql-languages-action@main
      with:
        exclude_codeql_languages: ${{inputs.exclude_codeql_languages}}
        
  codeql-analysis:
    needs: [detect-lang]
    # skip the analysis when the list of languages is empty
    if: needs.detect-lang.outputs.codeql_languages != '[]'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ${{ fromJSON(needs.detect-lang.outputs.codeql_languages) }}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Check CodeQL config existence
      id: custom_codeql_config
      uses: andstor/file-existence-action@v2
      with:
        files: "./.github/codeql/codeql-config.yml"
        
    - name: Initialize CodeQL custom
      if: steps.custom_codeql_config.outputs.files_exists == 'true'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql/codeql-config.yml
        
    - name: Initialize CodeQL default
      if: steps.custom_codeql_config.outputs.files_exists == 'false'
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: mbaluda-org/security_team/codeql-config.yml@main
    
    - name: Check local build action existence
      id: custom_build_action
      uses: andstor/file-existence-action@v2
      with:
        files: "./.github/actions/custom_build/action.yml"
        
    - name: Build custom
      if: steps.custom_build_action.outputs.files_exists == 'true'
      uses: ./.github/actions/custom_build
      with:
        languages: ${{ matrix.language }}

    - name: Build default
      if: steps.custom_build_action.outputs.files_exists == 'false'
      uses: github/codeql-action/autobuild@v2
      id: autobuild
      continue-on-error: true
      
    - uses: mainmatter/continue-on-error-comment@v1
      if: steps.custom_build_action.outputs.files_exists == 'false'
      with:
        outcome: ${{ steps.autobuild.outcome }}
        test-id: Error code ${{ matrix.code }}

    - name: Build custom
      if: steps.custom_build_action.outputs.files_exists == 'true'
      uses: ./.github/actions/custom_build
      id: custombuild
      continue-on-error: true
      with:
        languages: ${{ matrix.language }}

    - uses: mainmatter/continue-on-error-comment@v1
      if: steps.custom_build_action.outputs.files_exists == 'true'
      with:
        outcome: ${{ steps.autobuild.outcome }}
        test-id: Error code ${{ matrix.code }}    

    # perform the analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
